name: Hugo Build/Beautify
runs:
  using: composite
  env:
    HUGO_VERSION: 0.114.0
  steps:
    # - name:  Variable checks
    #   run: echo "{{ github.repository }} / ${{ github.repository_owner }} / ${{ github.event.repository.name }}"
    #   shell: bash
    # - name: Install Hugo
    #   uses: peaceiris/actions-hugo@v2
    #   with:
    #     hugo-version: 0.114.0
    #     extended:     true
    - name: Install Hugo
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name:  Install Beautifier
      run:   npm -g install js-beautify@1.14.8
      shell: bash
    - name:  Install Sass (Dart)
      run: sudo snap install dart-sass-embedded
      shell: bash
    - name:  Build Hugo
      run:   hugo --minify
      shell: bash
    # - name: Build Hugo
    #   env:
    #     HUGO_ENVIRONMENT: ${{ github.job }}
    #   run: |
    #     hugo \
    #       --minify \
    #       --destination
    #       --baseURL ${{ steps.pages.outputs.base_url }}/
    #       --environment ${{ github.job }}
    - name:  Beautify Output
      run: |
        html-beautify --indent-inner-html --extra_liners --no-preserve-newlines --indent-with-tabs --replace "${{ env.destination }}/**/*.html"
        css-beautify --space_around_combinator --indent-with-tabs --replace "${{ env.destination }}/**/*.css"
        js-beautify --indent-with-tabs --replace "${{ env.destination }}/**/*.js"
      shell: bash
