name: Hugo Build, Beautify
inputs:
  destination:
    required: true
  environment:
    required: true
runs:
  using: composite
  steps:
    - name:  Variable checks
      run: echo ${{inputs.environment}}
      shell: bash
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.114.0
        extended:     true
    - name:  Install Beautifier
      run:   npm -g install js-beautify@1.14.8
      shell: bash
    - name:  Install Sass (Dart)
      run: sudo snap install dart-sass-embedded
      shell: bash
    - name:  Build Hugo
      run:   hugo --minify -d ${{inputs.destination}} --environment ${{inputs.environment}}
      shell: bash
    - name:  Beautify Output
      run: |
        html-beautify --indent-inner-html --extra_liners --no-preserve-newlines --indent-with-tabs --replace "${{inputs.destination}}/**/*.html"
        css-beautify --space_around_combinator --indent-with-tabs --replace "${{inputs.destination}}/**/*.css"
        js-beautify --indent-with-tabs --replace "${{inputs.destination}}/**/*.js"
      shell: bash
