name: Hugo Build/Beautify
runs:
  using: composite
  steps:
    - name: Install Hugo
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      shell: bash
    - name:  Install Beautifier
      run:   npm -g install js-beautify@${BEAUTIFY_VERSION}
      shell: bash
    - name:  Install Sass (Dart)
      run:   sudo snap install dart-sass-embedded
      shell: bash
    - name:  Build Hugo
      run:   hugo --minify --baseURL ${HUGO_BASEURL} --destination _site
      shell: bash
    - name:  Beautify Output
      run: |
        html-beautify --indent-inner-html --extra_liners --no-preserve-newlines --indent-with-tabs --replace "_site/**/*.html"
        css-beautify --space_around_combinator --indent-with-tabs --replace "_site/**/*.css"
        js-beautify --indent-with-tabs --replace "_site/**/*.js"
      shell: bash
