name: Hugo Build/Beautify
runs:
  using: composite
  steps:
    # - name:  Variable checks
    #   run: echo "{{ github.repository }} / ${{ github.repository_owner }} / ${{ github.event.repository.name }}"
    #   shell: bash
    - name: Install Hugo
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${hugo-version}/hugo_extended_${hugo-version}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      shell: bash
    - name:  Install Beautifier
      run:   npm -g install js-beautify@${beautify-version}
      shell: bash
    - name:  Install Sass (Dart)
      run: sudo snap install dart-sass-embedded
      shell: bash
    - name: Build Hugo
      run: |
        hugo \
          --minify \
          --destination public
          --baseURL ${{ steps.pages.outputs.base_url }}/
          --environment ${{ github.job }}
      shell: bash
    - name:  Beautify Output
      run: |
        html-beautify --indent-inner-html --extra_liners --no-preserve-newlines --indent-with-tabs --replace "public/**/*.html"
        css-beautify --space_around_combinator --indent-with-tabs --replace "public/**/*.css"
        js-beautify --indent-with-tabs --replace "public/**/*.js"
      shell: bash
