name: Update README
runs:
  using: composite
  steps:
    - name: Edit link
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find:    \((.*?) "Gorbachev"\)
        replace: (${HUGO_BASEURL}/bookmarklet.txt "Gorbachev")
        include: .github/README.md
    - name: Commit changes
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update bookmarklet link."
          git push
        fi
      shell: bash
    # - name: Store the bookmarklet
    #   id: bookmarklet
    #   run: echo "link=$(cat _site/bookmarklet.txt)" >> "$GITHUB_OUTPUT"
    #   shell: bash
    # - name: Get the bookmarklet
    #   run: echo "Bookmarklet is ${{ steps.bookmarklet.outputs.link }}"
    #   shell: bash
