name: Update README
runs:
  using: composite
  steps:
    - name: Edit link
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find:    '\((.*?) "Gorbachev"\)'
        replace: '(${{ steps.pages.outputs.base_url }}/bookmarklet.txt "Gorbachev")'
        include: '**README.md'
      shell: bash
    - name: Commit changes
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update bookmarklet link."
          git push
        fi
      shell: bash
    # - name: Store the bookmarklet
    #   id: bookmarklet
    #   run: echo "link=$(cat _site/bookmarklet.txt)" >> "$GITHUB_OUTPUT"
    # - name: Get the bookmarklet
    #   run: echo "Bookmarklet is ${{ steps.bookmarklet.outputs.link }}"
