name: Automatic build/deploy
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages:    write
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Pages
      id:   pages
      uses: actions/configure-pages@v3
    - name: Build Hugo
      uses: ./.github/actions/hugo-build-beautify
      env:
        BEAUTIFY_VERSION: 1.14.8
        HUGO_VERSION:     0.114.0
        HUGO_BASEURL:     ${{ steps.pages.outputs.base_url }}
        HUGO_PARAMS_URL:  ${{ github.server_url }}/${{ github.repository }}
    - name: Store the bookmarklet
      run: echo "bookmarklet=$(cat _site/bookmarklet.txt)" >> $GITHUB_ENV
    - name: Read the bookmarklet
      run: echo ${{ env.bookmarklet }}
      # env:
      #   BOOKMARKLET: cat _site/bookmarklet.txt
      # run: echo ${BOOKMARKLET}
      # run:  cat _site/bookmarklet.txt
      # run: echo _site/bookmarklet.txt >> $GITHUB_ENV
    # - name: Upload bookmarklet
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: bookmarklet
    #     path: _site/bookmarklet.txt
    - name: Upload output
      uses: actions/upload-pages-artifact@v1
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
