name: Automatic build/deploy
on:
  push:
    branches: [main]
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/hugo-build-beautify
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token:   ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir:    ./${{ env.destination }}
    #     publish_branch: ${{ env.destination }}
    #     commit_message: ${{ github.event.head_commit.message }}
