name: Automatic build/deploy
on:
  push:
    branches: [main]
env:
  destination: public
jobs:
  github:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/hugo-build-beautify
      with:
        base_url:    ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        destination: ${{ env.destination }}
        environment: github
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:   ${{ secrets.GITHUB_TOKEN }}
        publish_dir:    ./${{ env.destination }}
        publish_branch: ${{ env.destination }}
        commit_message: ${{ github.event.head_commit.message }}
