name: Automatic build/deploy
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  pages:    write
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Pages
      id:   pages
      uses: actions/configure-pages@v3
    - name: Edit README
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find:    HUGO_BASEURL
        replace: ${{ steps.pages.outputs.base_url }}
        include: '**README.md'
    - name: Commit README
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto-updated bookmarklet link."
          git push
        fi
    - name: Build Hugo
      uses: ./.github/actions/hugo-build-beautify
      env:
        BEAUTIFY_VERSION: 1.14.8
        HUGO_VERSION:     0.114.0
        HUGO_BASEURL:     ${{ steps.pages.outputs.base_url }}
        HUGO_PARAMS_URL:  ${{ github.server_url }}/${{ github.repository }}
    # - name: Store the bookmarklet
    #   id: bookmarklet
    #   run: echo "link=$(cat _site/bookmarklet.txt)" >> "$GITHUB_OUTPUT"
    # - name: Get the bookmarklet
    #   run: echo "Bookmarklet is ${{ steps.bookmarklet.outputs.link }}"
    - name: Upload output
      uses: actions/upload-pages-artifact@v1
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
