name: Automatic build/deploy
on:
  push:
    branches: [$default-branch]
  # Allow manual triggering
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Build Hugo
      uses: ./.github/actions/hugo-build-beautify
      with:
        base-url:         ${{ steps.pages.outputs.base_url }}
        beautify-version: 1.14.8
        hugo-version:     0.114.0
    - name: Upload output
      uses: actions/upload-pages-artifact@v1
      with:
        path: public
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
