name: Automatic build/deploy
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  pages:    write
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Pages
      id:   pages
      uses: actions/configure-pages@v3
    - name: Build Hugo
      env:
        BEAUTIFY_VERSION: 1.14.8
        HUGO_BASEURL:     ${{ steps.pages.outputs.base_url }}
        HUGO_VERSION:     0.114.0
        HUGO_PARAMS_URL:  ${{ github.server_url }}/${{ github.repository }}
      uses: ./.github/actions/hugo-build-beautify
    - name: Update README
      env:
        HUGO_BASEURL: ${{ steps.pages.outputs.base_url }}
      uses: ./.github/actions/update-readme
    - name: Upload output
      uses: actions/upload-pages-artifact@v1
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
