name: GitHub Pages
on:
  push:
    branches: [main]
env:
  destination: public
jobs:
  build-deploy:
    name:    Build/Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.114.0
        extended:     true
    - name: Setup Beautifier
      run:  npm -g install js-beautify@1.14.0
    - name: Build
      run:  hugo --minify -d ${{ env.destination }}
    - name: Beautify HTML
      run:  html-beautify --indent-inner-html --extra_liners --no-preserve-newlines --indent-with-tabs --replace "${{ env.destination }}/**/*.html"
    - name: Beautify CSS
      run:  css-beautify --space_around_combinator --indent-with-tabs --replace "${{ env.destination }}/**/*.css"
    - name: Beautify JS
      run:  js-beautify --indent-with-tabs --replace "${{ env.destination }}/**/*.js"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:    ${{ secrets.GITHUB_TOKEN }}
        publish_dir:    ./${{ env.destination }}
        publish_branch: ${{ env.destination }}
        commit_message: ${{ github.event.head_commit.message }}
